name: geary
summary: Send and receive email 
description: Geary is an email application built around conversations, for the GNOME 3 desktop.
  
adopt-info: devmode # use 'strict' once you have the right plugs and slots

grade: stable
confinement: devmode

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

apps:
  geary:
    command: bin/geary
    plugs:
      - home
      - network

parts:
geary:
    plugin: 
    source: https://github.com/GNOME/geary.git
    source-type: git
    override-pull: |
     git clone https://github.com/GNOME/geary.git src/github.com/GNOME/geary
       cd src/github.com/GNOME/geary
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | sed 's/v//')"
      override-build: |
      export GOPATH=$PWD
      cd src/github.com/GNOME/geary
      env CGO_ENABLED=0 GOOS=linux \
      go build --ldflags "-s -w \
        -X 'github.com/GNOME/geary/version.GitCommit=$(git rev-list -1 HEAD)' \
        -X 'github.com/GNOME/geary/version.Version=$(git describe --tags --abbrev=0)'" \
        -a -installsuffix cgo -o $SNAPCRAFT_PART_INSTALL/bin/geary
    build-snaps:
      - vala
    build-packages:
      - git
      - sed
