name: timeshift
summary: System restore tool. 
description: A system restore tool for Linux. 
  
adopt-info: devmode # use 'strict' once you have the right plugs and slots

grade: stable
confinement: devmode

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

apps:
  timeshift:
    command: bin/timeshift
    plugs:
      - home
      - network
      - removable-media

parts:
timeshift:
    plugin: 
    source: https://github.com/teejee2008/timeshift.git
    source-type: git
    override-pull: |
     git clone https://github.com/teejee2008/timeshift.git src/github.com/teejee2008/timeshift
       cd src/github.com/teejee2008/timeshift
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags | sed 's/v//')"
      override-build: |
      export GOPATH=$PWD
      cd src/github.com/teejee2008/timeshift
      env CGO_ENABLED=0 GOOS=linux \
      go build --ldflags "-s -w \
        -X 'github.com/teejee2008/timeshift/version.GitCommit=$(git rev-list -1 HEAD)' \
        -X 'github.com/teejee2008/timeshift/version.Version=$(git describe --tags --abbrev=0)'" \
        -a -installsuffix cgo -o $SNAPCRAFT_PART_INSTALL/bin/timeshift
    build-snaps:
      - vala
    build-packages:
      - git
      - sed
